title: Services
template: default
layout: layout
revisions: false
route: '/services/{slug}'
orderable: true
sort_by: order
sort_dir: asc
preview_targets:
  -
    label: Entry
    url: '{permalink}'
    refresh: true
